// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9bQMnPMiHbfXLMWspmaZXTPmUruKwvA',
    appId: '1:342964023816:android:33cbffffa8c3b6ed5e57bd',
    messagingSenderId: '342964023816',
    projectId: 'crud-1fddf',
    storageBucket: 'crud-1fddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmo--a0axiiTT1lOZ_ns1TvNiVdUemtdE',
    appId: '1:342964023816:ios:d4c52006a7fdaf1c5e57bd',
    messagingSenderId: '342964023816',
    projectId: 'crud-1fddf',
    storageBucket: 'crud-1fddf.firebasestorage.app',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8pAzAusepI9yaMncO1EV4hrfqJ6DQf-M',
    appId: '1:342964023816:web:98adb96405562abe5e57bd',
    messagingSenderId: '342964023816',
    projectId: 'crud-1fddf',
    authDomain: 'crud-1fddf.firebaseapp.com',
    storageBucket: 'crud-1fddf.firebasestorage.app',
  );

}